# Generated by Django 2.2.4 on 2020-01-18 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bottles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BottleStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottle_primary_key', models.IntegerField()),
                ('level', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('rate', models.FloatField(blank=True, default=None, null=True)),
                ('estimated_time_left', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('disease', models.CharField(max_length=100)),
                ('room_number', models.IntegerField()),
                ('bed_number', models.IntegerField()),
                ('bottle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Bottles')),
            ],
        ),
    ]
